spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service_db
    username: postgres
    password: "%Nw8Fm1qc*HXFh3mK}|9GOzATC}8LQrh"
library-service:
  secret-key: "ahgNSFHEKdbmrVvmKV2GmDGRTOzVAjsJD8k7crjR5yM="
  base-url: http://localhost:8082